# Changes here will be overwritten by Copier
_commit: 2.0.0
_src_path: gh:markusritschel/cookiecutter-pyproject
command_line_interface: Click
docs_engine: Sphinx
github_user: markusritschel
is_research_project: false
package_name: dkrz_cera
project_description: An interface to the CERA database of the DKRZ (Deutsches Klimarechenzentrum)
project_license: MIT license
project_name: DKRZ-CERA
project_slug: dkrz-cera
project_version: 0.1.0
user_email: git@markusritschel.de
user_name: Markus Ritschel

